snt/bookings/urls.py
from django.urls import path
from . import views

app_name="bookings"
urlpatterns=[
    path('', views.Bookings.as_view(), name='all'),
    path('bookings/<int:pk>/update/', views.UpdateBookings.as_view(), name='booking_update'),
    path('bookings/<int:pk>/delete/', views.DeleteBookings.as_view(), name='booking_confirm_delete'),
]

snt/home/urls.py
from django.urls import path
from . import views
# from django.contrib.auth import views as auth_views
app_name='home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='all'),
    # path("register",views.register,name="register"),
]

snt/snt/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('newbooking/', include('newbooking.urls')),
    path('bookings/', include('bookings.urls')),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')),
]

snt/user/urls.py
from django.urls import path
from . import views
# from django.contrib.auth import views as auth_views
app_name = 'user'
urlpatterns = [
    path('', views.SignUp.as_view(), name='all'),
    path('userprofile/', views.ProfileUpdate.as_view(), name='profile_update'),
    path('passwordchange/', views.PasswordChangeView.as_view(), name='password_change'),
]

snt/home/views.py
from django.shortcuts import render
from django.views import View
from django.conf import settings

class HomeView(View):
    def get(self, request):
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal
        }
        return render(request, 'home/main.html', context)

snt/home/templates/home/main.html
{% load static %}
{% block head %}
  <head>
    <meta charset="UTF-8"><link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

    <link rel="shortcut icon" href="{% static '/favicon.ico' %}" />
  </head>
  {% endblock %}
{% load crispy_forms_tags %}
<h1>Home Page</h1>
<ul>
    <li>
        <a href="{% url 'bookings:all' %}">Booking</a>
    </li>
    <li>
        <a href="{% url 'newbooking:all' %}">New Booking</a>
    </li>
    <li>
        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}?next={% url 'home:all' %}">Logout</a> / <a href="{% url 'user:profile_update' %}">Profile</a> / <a href="{% url 'user:password_change' %}">Password Change</a>
        {% else %}
        <a href="{% url 'login' %}?next={% url 'home:all' %}">Login</a> / <a href="{% url 'user:all' %}?next={% url 'home:all' %}">Register</a>
        {% endif %}
    </li>
</ul>