snt/bookings/urls.py
from django.urls import path
from . import views

app_name="bookings"
urlpatterns=[
    path('', views.Bookings.as_view(), name='all'),
    path('bookings/<int:pk>/update/', views.UpdateBookings.as_view(), name='booking_update'),
    path('bookings/<int:pk>/delete/', views.DeleteBookings.as_view(), name='booking_confirm_delete'),
]

snt/snt/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('newbooking/', include('newbooking.urls')),
    path('bookings/', include('bookings.urls')),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')),
]

snt/newbooking/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxValueValidator, MinValueValidator
from django.conf import settings

class Package(models.Model):
    destination = models.CharField(max_length=300)
    def __str__(self):
        return self.destination

class Conveyance(models.Model):
    conveyance=models.CharField(max_length=300)
    def __str__(self):
        return self.conveyance


class Booking(models.Model):
    name = models.CharField(max_length=200, validators=[MinLengthValidator(2,"Name must be greater than 1 character")])
    package = models.ForeignKey('Package',on_delete=models.CASCADE, null=False)
    date = models.DateField()
    no_of_People=models.IntegerField(validators=[MinValueValidator(1,"Atleast one person should be on the trip!Or are you a Ghost?"), MaxValueValidator(30,"Bro a bus can only fit 30 people")])
    preferred_mode_of_travel=models.ForeignKey('Conveyance',on_delete=models.CASCADE)
    any_special_requests=models.TextField(null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=True)
    status = models.CharField(max_length=200,default='Not Confirmed')
    def __str__(self):
        return self.name

class Price(models.Model):
    cost=models.IntegerField(null=False)
    destination=models.ForeignKey('Package',on_delete=models.CASCADE,null=False)
    def __str__(self):
        return str(self.cost)

snt/bookings/views.py
from django.shortcuts import render
from newbooking.models import Booking
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from bookings.owner import OwnerUpdateView, OwnerDeleteView
from django.urls import reverse_lazy
from django.contrib.auth.models import User

class Bookings(LoginRequiredMixin, View):
    def get(self,request):
        booking_list=Booking.objects.filter(owner=self.request.user, status="Confirmed")
        ctx={'booking_list':booking_list}
        return render(request,'bookings/booking_list.html',ctx)
# Create your views here.

class UpdateBookings(OwnerUpdateView):
    model=Booking
    fields=['name','date','any_special_requests','preferred_mode_of_travel']
    template_name= 'bookings/booking_update_form.html'
    success_url=reverse_lazy('bookings:all')

class DeleteBookings(OwnerDeleteView):
    model=Booking
    template_name= 'bookings/booking_confirm_delete.html'
    success_url=reverse_lazy('bookings:all')

snt/bookings/templates/bookings/booking_confirm_delete.html
<p>Are you sure you want to cancel?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes.">
  <input type="submit" onclick="window.location='{% url 'bookings:all' %}' ; return false;" value="Cancel">

</form>

snt/bookings/templates/bookings/booking_list.html
<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>
<h1>Booking List</h1>
<ul>
    {% for booking in booking_list %}
    <li><p>
        {{ booking.name }}
</p><p>package- {{ booking.package }}</p><p><a href="{% url 'bookings:booking_update' booking.id %}">Update Booking</a><a href="{% url 'bookings:booking_confirm_delete' booking.id %}"> Delete Booking</a>
</p></li> {% endfor %}</ul>

snt/bookings/templates/bookings/booking_update_form.html
 <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css"><script>
  $(function() {
    $( "#id_date" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "2020:2022",
      // You can put more options here.

    });
  });
  </script>
  <style>.ui-datepicker .ui-datepicker-title select {
    color: #000;

}</style>
{% load crispy_forms_tags %}
<form method="post">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Update">
</form>