snt/bookings/urls.py
from django.urls import path
from . import views

app_name="bookings"
urlpatterns=[
    path('', views.Bookings.as_view(), name='all'),
    path('bookings/<int:pk>/update/', views.UpdateBookings.as_view(), name='booking_update'),
    path('bookings/<int:pk>/delete/', views.DeleteBookings.as_view(), name='booking_confirm_delete'),
]

snt/home/urls.py
from django.urls import path
from . import views
# from django.contrib.auth import views as auth_views
app_name='home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='all'),
    # path("register",views.register,name="register"),
]

snt/newbooking/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name="newbooking"
urlpatterns=[
    path('', views.NewBookingCreate.as_view(), name='all'),
    path('newbooking/<int:pk>', views.ConfirmBooking.as_view(), name='confirm_booking'),
    path('newbooking/<int:pk>/delete', views.NewBookingDeleteView.as_view(success_url=reverse_lazy('newbooking:all')), name='newbooking_delete'),
]

snt/snt/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('newbooking/', include('newbooking.urls')),
    path('bookings/', include('bookings.urls')),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')),
]

snt/newbooking/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxValueValidator, MinValueValidator
from django.conf import settings

class Package(models.Model):
    destination = models.CharField(max_length=300)
    def __str__(self):
        return self.destination

class Conveyance(models.Model):
    conveyance=models.CharField(max_length=300)
    def __str__(self):
        return self.conveyance


class Booking(models.Model):
    name = models.CharField(max_length=200, validators=[MinLengthValidator(2,"Name must be greater than 1 character")])
    package = models.ForeignKey('Package',on_delete=models.CASCADE, null=False)
    date = models.DateField()
    no_of_People=models.IntegerField(validators=[MinValueValidator(1,"Atleast one person should be on the trip!Or are you a Ghost?"), MaxValueValidator(30,"Bro a bus can only fit 30 people")])
    preferred_mode_of_travel=models.ForeignKey('Conveyance',on_delete=models.CASCADE)
    any_special_requests=models.TextField(null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=True)
    status = models.CharField(max_length=200,default='Not Confirmed')
    def __str__(self):
        return self.name

class Price(models.Model):
    cost=models.IntegerField(null=False)
    destination=models.ForeignKey('Package',on_delete=models.CASCADE,null=False)
    def __str__(self):
        return str(self.cost)

snt/newbooking/forms.py
from django import forms
from newbooking.models import Booking

class CreateForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['name','package','date','no_of_People','preferred_mode_of_travel','any_special_requests']
        widgets = {'date': forms.DateInput(attrs={'class':'datepicker'})}

snt/bookings/views.py
from django.shortcuts import render
from newbooking.models import Booking
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from bookings.owner import OwnerUpdateView, OwnerDeleteView
from django.urls import reverse_lazy
from django.contrib.auth.models import User

class Bookings(LoginRequiredMixin, View):
    def get(self,request):
        booking_list=Booking.objects.filter(owner=self.request.user, status="Confirmed")
        ctx={'booking_list':booking_list}
        return render(request,'bookings/booking_list.html',ctx)
# Create your views here.

class UpdateBookings(OwnerUpdateView):
    model=Booking
    fields=['name','date','any_special_requests','preferred_mode_of_travel']
    template_name= 'bookings/booking_update_form.html'
    success_url=reverse_lazy('bookings:all')

class DeleteBookings(OwnerDeleteView):
    model=Booking
    template_name= 'bookings/booking_confirm_delete.html'
    success_url=reverse_lazy('bookings:all')

snt/newbooking/views.py
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from newbooking.owner import OwnerDeleteView, OwnerUpdateView
from django.urls import reverse
from newbooking.forms import CreateForm
from newbooking.models import Booking, Price
from django.shortcuts import render, redirect


class NewBookingDeleteView(OwnerDeleteView):
    model = Booking
    success_url='newbooking:all'


class NewBookingCreate(LoginRequiredMixin, View):
    template_name='newbooking/booking_form.html'
    success_url='newbooking:all'
    def get(self,request,pk=None):
        form=CreateForm()
        ctx={'form':form}
        return render(request,self.template_name,ctx)

    def post(self,request,pk=None):
        form=CreateForm(request.POST)
        if not form.is_valid():
            ctx={'form':form}
            return render(request,self.template_name,ctx)

        booking=form.save(commit=False)
        booking.owner=self.request.user
        booking.save()
        return redirect(reverse('newbooking:confirm_booking', args=[booking.id]))


class ConfirmBooking(LoginRequiredMixin, View):
    def get(self,request,pk):
        booking=Booking.objects.get(id=pk)
        y=Price.objects.get(destination=booking.package)
        x=booking.no_of_People
        z=y.cost
        z=z*x
        ctx={'booking':booking,'cost':z}
        return render(request,'newbooking/confirm_booking.html',ctx)

    def post(self,request,pk):
        booking=Booking.objects.get(id=pk)
        booking.status='Confirmed'
        booking.save()
        return redirect('home:all')

snt/newbooking/templates/newbooking/booking_confirm_delete.html
<p>Are you sure you want to cancel?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes.">
    <input type="submit" onclick="window.location='{% url 'newbooking:confirm_booking' booking.id %}' ; return false;" value="Cancel">
</form>

snt/newbooking/templates/newbooking/booking_form.html
<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">
  <script>
  $(function() {
    $( ".datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "2020:2022",
      // You can put more options here.

    });
  });
  </script>
  <style>.ui-datepicker .ui-datepicker-title select {
    color: #000;

}</style>
<form action="" method="post">
    {% csrf_token %}
    {% load crispy_forms_tags %}
    <table>
    {{ form|crispy }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'home:all' %}' ; return false;" value="Cancel">
  </form>

snt/newbooking/templates/newbooking/confirm_booking.html
<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>
<h1>
    Total Cost= {{ cost }}
    <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Book">
    <input type="submit" onclick="window.location='{% url 'newbooking:newbooking_delete' booking.id %}' ; return false;" value="Cancel">
</form>
</h1>

snt/newbooking/templates/newbooking/newbooking_form.html
 <form action="" method="post">
    {% csrf_token %}
    {% load crispy_forms_tags %}
    <table>
    {{ form.as_p }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'newbooking:all' %}' ; return false;" value="Cancel">
  </form>